services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3002:5173"
    volumes:
      - ./app:/app 
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["npm", "run", "dev"]

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3002:80"